name: Ecommerce Context Sample

on:
  workflow_dispatch:

env:
  CURVERSION: V_2025_Q2_R1.1 # Using env local variable

jobs:
  test:
    strategy:
      matrix:
        service: [cart, payment, inventory, user]  # Using matrix
    runs-on: ubuntu-latest
    outputs:
      test-status: ${{ steps.set-output.outputs.status }}
    steps:
      - name: Run tests
        run:  echo "Running tests for ${{ matrix.service }}"

      - id: set-output
        run:  echo "status=success" >> $GITHUB_OUTPUT
          
  deploy:
    needs: test      # Using needs
    if: needs.test.outputs.test-status == 'success' # Using needs and outputs
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: ${{ vars.DEPLOY_ENV }} #Using vars
    steps:
      - name: Deploy service
        run: |
          echo "Current Version : ${{ CURVERSION  }}" #Using Local variable
          echo "Deploying services to $DEPLOY_ENV"   #Using Local variable
          echo "Using secret: ${{ secrets.DEPLOY_KEY }}" #Using secrets
          echo "Repository Details: ${{ github.repository }}" # Using github
          echo "Repository OwnerName: ${{ github.repository_owner }}" # Using github
          echo "Repository URL: ${{ github.repositoryUrl }}" # Using github
          echo "Repository Run Attempt: ${{ github.run_attempt }}" # Using github
          echo "Repository Server Url: ${{ github.server_url }}" # Using github

          
