name: Manual Workflow with Functions

on:
  workflow_dispatch:  

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Define and use a shell function
        run: |
          greet_user() {
            echo "Hello, $1!"
          }

          greet_user "Suriya"

