name: Manual Workflow with Variables
on:
  workflow_dispatch:  
  
jobs:
  simulate-comment:
    runs-on: ubuntu-latest
    env:
      COMMENT_STATUS: failed  

    steps:
      - name: Check comment status
        run: |
          if [ "${COMMENT_STATUS}" == "failed" ]; then
            echo "There was a problem saving your comment. Please try again."
          else
            echo "Comment saved successfully."
          fi
