name: Matrix with Java Versions and Fail-Fast

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: cart
            java: 17
            index: 0
            total: 4
          - service: cart
            java: 21
            index: 1
            total: 4
          - service: payment
            java: 17
            index: 2
            total: 4
          - service: payment
            java: 21
            index: 3
            total: 4
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Show matrix info
        run: |
          echo "Service: ${{ matrix.service }}"
          echo "Java Version: ${{ matrix.java }}"
          echo "Index: ${{ matrix.index }} of ${{ matrix.total }}"
          java -version
