name: Matrix with Index and Total

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: cart
            environment: dev
            index: 0
            total: 4
          - service: cart
            environment: production
            index: 1
            total: 4
          - service: payment
            environment: dev
            index: 2
            total: 4
          - service: payment
            environment: production
            index: 3
            total: 4
    runs-on: ubuntu-latest
    steps:
      - name: Show matrix info
        run: |
          echo "Running test for service: ${{ matrix.service }}"
          echo "Environment: ${{ matrix.environment }}"
          echo "Index: ${{ matrix.index }} of ${{ matrix.total }}"
