name: Scheduled Workflow

on:
  schedule:
    - cron: '* * * * *' 

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "This workflow ran on schedule at $(date)"
