
name: Scheduled Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "This workflow ran on schedule at $(date)"
