name : Setup Python
on:   
  workflow_dispatch: 
jobs:
  java-setup:
    runs-on: ubuntu-latest
  
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version:  '3.11'  
        architecture: 'x64'
        check-latest: true
        update-environment: true
        allow-prereleases: false
        cache: 'pip'
