name : Setup Java
on:   
  workflow_dispatch: 
jobs:
  runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
